import type { Photo, Poi, PoiKind, Property, T } from "./types";

/* ---------------------------------------------------------------------------
   The portfolio. Twenty-four listings, priced against the Chisinau market:
   the area sits inside the band for its room count, the price inside the band
   for its sector, and pricePerSqm is stored rather than divided in JSX.

   Photography follows one rule for the whole site — 3:2, 1600x1067 — so a card
   never reflows while the image lands.
   --------------------------------------------------------------------------- */

const ROOM = {
  living: { ro: "Living", ru: "Гостиная" },
  kitchen: { ro: "Bucătărie", ru: "Кухня" },
  bedroom: { ro: "Dormitor", ru: "Спальня" },
  bath: { ro: "Baie", ru: "Ванная" },
  dining: { ro: "Zonă de luat masa", ru: "Обеденная зона" },
  study: { ro: "Birou", ru: "Кабинет" },
  facade: { ro: "Fațada clădirii", ru: "Фасад здания" },
  house: { ro: "Exteriorul casei", ru: "Внешний вид дома" },
  space: { ro: "Spațiul", ru: "Помещение" },
} as const;

type RoomKey = keyof typeof ROOM;

/** What each file in public/img actually shows, so alt text is never generic. */
const SHOWS: Record<string, RoomKey> = {
  "apt-01": "living",
  "apt-02": "living",
  "apt-03": "kitchen",
  "apt-04": "bedroom",
  "apt-05": "bedroom",
  "apt-06": "living",
  "apt-07": "kitchen",
  "apt-08": "bath",
  "apt-09": "dining",
  "apt-10": "living",
  "apt-11": "bedroom",
  "apt-12": "kitchen",
  "apt-13": "living",
  "apt-14": "living",
  "apt-15": "dining",
  "apt-16": "living",
  "apt-17": "bath",
  "apt-18": "kitchen",
  "apt-19": "study",
  "apt-20": "living",
  "house-01": "house",
  "house-02": "house",
  "house-03": "house",
  "house-04": "house",
  "block-01": "facade",
  "block-02": "facade",
  "block-03": "facade",
  "block-04": "facade",
  "block-05": "facade",
  "block-06": "facade",
  office: "space",
};

/** Builds the gallery. The first frame is what the card shows. */
function shots(names: string[], place: string): Photo[] {
  return names.map((n) => ({
    src: `/img/${n}.jpg`,
    width: 1600,
    height: 1067,
    alt: {
      ro: `${ROOM[SHOWS[n]].ro}, ${place}`,
      ru: `${ROOM[SHOWS[n]].ru}, ${place}`,
    },
  }));
}

const poi = (kind: PoiKind, ro: string, ru: string, meters: number): Poi => ({
  kind,
  name: { ro, ru },
  meters,
});

const NOW: T = { ro: "Imediat", ru: "Сразу" };

/** Every listing points at the same generated city map; the marker is placed
 *  from `coords` by the component that renders it. */
const MAP = "/harti/chisinau.jpg";

export const PROPERTIES: Property[] = [
  {
    id: "AR-1042",
    slug: "apartament-3-camere-matei-basarab-riscani-ar-1042",
    deal: "vanzare",
    kind: "apartament",
    status: "activ",
    flags: ["exclusivitate", "gata-de-mutat"],
    title: {
      ro: "Apartament cu 3 camere, str. Matei Basarab, Râșcani",
      ru: "3-комнатная квартира, ул. Матей Басараб, Рышкановка",
    },
    description: {
      ro: "Apartament cu trei camere într-un bloc dat în exploatare în 2022, la două străzi de parcul Râșcani. Proprietarii au făcut reparația o singură dată, cu materiale alese fără grabă, și au locuit în el mai puțin de doi ani. Ferestrele living-ului dau spre curtea interioară, deci dimineața nu te trezește bulevardul.\n\nCompartimentare: antreu cu dulap încastrat, living cu ieșire pe balcon, două dormitoare, bucătărie separată de 11 m², două blocuri sanitare, debara.\n\nFacilități: încălzire autonomă cu centrală Viessmann, geamuri termopan cu profil de șase camere, aer condiționat în living și în dormitorul mare, ușă metalică cu trei puncte de închidere, tehnică electrocasnică inclusă.\n\nFacilitățile blocului: parcare subterană cu loc atribuit, lift silențios de la Kone, videointerfon, curte închisă cu barieră și teren de joacă, pază 24/24.",
      ru: "Трёхкомнатная квартира в доме, сданном в 2022 году, в двух улицах от парка Рышкановка. Собственники делали ремонт один раз, материалы выбирали не торопясь, и прожили здесь меньше двух лет. Окна гостиной выходят во внутренний двор, так что по утрам вас не будит бульвар.\n\nПланировка: прихожая со встроенным шкафом, гостиная с выходом на балкон, две спальни, отдельная кухня 11 м², два санузла, кладовая.\n\nУдобства: автономное отопление с котлом Viessmann, шестикамерные стеклопакеты, кондиционеры в гостиной и большой спальне, металлическая дверь с тремя точками запирания, бытовая техника включена.\n\nВ доме: подземный паркинг с закреплённым местом, тихий лифт Kone, видеодомофон, закрытый двор со шлагбаумом и детской площадкой, охрана 24/7.",
    },
    landmark: { ro: "lângă parcul Râșcani", ru: "рядом с парком Рышкановка" },
    price: 155000,
    pricePerSqm: 1987,
    negotiable: true,
    rooms: 3,
    bedrooms: 2,
    bathrooms: 2,
    area: 78,
    livingArea: 52,
    kitchenArea: 11,
    floor: 4,
    floors: 9,
    ceilingHeight: 275,
    balconies: 1,
    sector: "riscani",
    street: "str. Matei Basarab 12",
    coords: { lat: 47.0512, lng: 28.8564 },
    mapImage: MAP,
    poi: [
      poi("transport", "Stație troleibuz 8, 22", "Остановка троллейбуса 8, 22", 140),
      poi("gradinita", "Grădinița 132", "Детский сад 132", 260),
      poi("magazin", "Linella", "Linella", 210),
      poi("parc", "Parcul Râșcani", "Парк Рышкановка", 700),
    ],
    fund: "bloc-nou",
    year: 2022,
    yearStatus: "finalizat",
    buildingType: "monolit",
    condition: "euroreparatie",
    layout: "decomandat",
    heating: "autonoma",
    parking: "subteran",
    amenities: [
      "parcare",
      "balcon",
      "lift",
      "centrala-termica",
      "mobilat",
      "tehnica",
      "aer-conditionat",
      "curte-inchisa",
      "videointerfon",
      "paza",
      "geamuri-termopan",
      "teren-joaca",
    ],
    developer: "Exfactor Grup",
    availableFrom: NOW,
    agentSlug: "victor-morari",
    photos: shots(
      ["apt-01", "apt-09", "block-01", "apt-04", "apt-12", "apt-08", "apt-13", "apt-05", "apt-18"],
      "str. Matei Basarab 12"
    ),
    publishedAt: "2026-07-09",
    updatedAt: "2026-07-24",
    featured: true,
  },
  {
    id: "AR-1108",
    slug: "apartament-2-camere-alexandru-cel-bun-centru-ar-1108",
    deal: "vanzare",
    kind: "apartament",
    status: "activ",
    flags: [],
    title: {
      ro: "Apartament cu 2 camere, str. Alexandru cel Bun, Centru",
      ru: "2-комнатная квартира, ул. Александру чел Бун, Центр",
    },
    description: {
      ro: "Apartament de două camere într-o clădire de cărămidă din 1974, pe o stradă liniștită la cinci minute de Ștefan cel Mare. Tavanele de 2,8 m și pereții groși țin apartamentul răcoros vara — lucru rar în Centru. Reparația e curată și funcțională, făcută acum patru ani, fără pretenții de design.\n\nCompartimentare: antreu, living, dormitor, bucătărie de 9 m², baie cu cadă, balcon de 4 m² închis cu termopan.\n\nFacilități: geamuri termopan pe toată suprafața, instalație electrică schimbată complet, boiler electric, aer condiționat în living, mobilă rămâne la înțelegere.\n\nFacilitățile blocului: scară curată cu ușă la intrare pe cod, subsol uscat cu boxă proprie, curte cu copaci maturi și loc de parcare neatribuit. Blocul are asociație de locatari activă și acoperișul refăcut în 2023.",
      ru: "Двухкомнатная квартира в кирпичном доме 1974 года, на тихой улице в пяти минутах от Штефана чел Маре. Потолки 2,8 м и толстые стены держат прохладу летом — редкость для Центра. Ремонт аккуратный и функциональный, сделан четыре года назад, без дизайнерских амбиций.\n\nПланировка: прихожая, гостиная, спальня, кухня 9 м², ванная с ванной, балкон 4 м² застеклён стеклопакетом.\n\nУдобства: стеклопакеты по всей квартире, полностью заменённая электропроводка, электрический бойлер, кондиционер в гостиной, мебель остаётся по договорённости.\n\nВ доме: чистый подъезд с кодовым замком, сухой подвал с собственной кладовой, двор со взрослыми деревьями и парковкой без закрепления. В доме активное товарищество собственников, крыша перекрыта в 2023 году.",
    },
    landmark: { ro: "la cinci minute de Ștefan cel Mare", ru: "в пяти минутах от Штефана чел Маре" },
    price: 152000,
    pricePerSqm: 2235,
    negotiable: true,
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    area: 68,
    livingArea: 42,
    kitchenArea: 9,
    floor: 3,
    floors: 5,
    ceilingHeight: 280,
    balconies: 1,
    sector: "centru",
    street: "str. Alexandru cel Bun 41",
    coords: { lat: 47.0261, lng: 28.8367 },
    mapImage: MAP,
    poi: [
      poi("transport", "Stație troleibuz 1, 4, 5", "Остановка троллейбуса 1, 4, 5", 180),
      poi("scoala", "Liceul Gheorghe Asachi", "Лицей Георге Асаки", 450),
      poi("magazin", "Fourchette", "Fourchette", 320),
      poi("parc", "Grădina Publică Ștefan cel Mare", "Парк Штефана чел Маре", 600),
    ],
    fund: "fond-vechi",
    year: 1974,
    yearStatus: "finalizat",
    buildingType: "caramida",
    condition: "reparatie-cosmetica",
    layout: "semidecomandat",
    heating: "centralizata",
    parking: "la-sol",
    amenities: [
      "balcon",
      "aer-conditionat",
      "geamuri-termopan",
      "pivnita",
      "mobilat",
      "bucatarie-separata",
      "internet",
    ],
    availableFrom: NOW,
    agentSlug: "andrei-cebotari",
    photos: shots(
      ["apt-02", "apt-07", "apt-11", "block-03", "apt-17", "apt-14", "apt-03", "apt-15"],
      "str. Alexandru cel Bun 41"
    ),
    publishedAt: "2026-06-28",
    updatedAt: "2026-07-21",
    featured: false,
  },
  {
    id: "AR-1156",
    slug: "apartament-1-camera-titulescu-botanica-ar-1156",
    deal: "vanzare",
    kind: "apartament",
    status: "activ",
    flags: [],
    title: {
      ro: "Apartament cu 1 cameră, str. Nicolae Titulescu, Botanica",
      ru: "1-комнатная квартира, ул. Николае Титулеску, Ботаника",
    },
    description: {
      ro: "Garsonieră de 42 m² la etajul 7, cu vedere deschisă spre Valea Trandafirilor. Reparația s-a terminat în 2024 și apartamentul n-a fost locuit de atunci — se vinde pentru că proprietarii au plecat din țară. Pentru un prim apartament sau pentru închiriat, e printre cele mai curate oferte pe care le avem în Botanica.\n\nCompartimentare: antreu, cameră de zi cu zonă de dormit separată printr-o bibliotecă, bucătărie de 8 m² deschisă spre living, baie cu duș, balcon lung închis.\n\nFacilități: încălzire centralizată cu calorifere noi și robinete termostatate, geamuri termopan, mobilă de bucătărie la comandă, mașină de spălat, frigider și plită cu inducție incluse.\n\nFacilitățile blocului: două lifturi funcționale, interfon, curte cu teren de joacă renovat în 2025 și parcare neatribuită. Troleibuzul spre Centru oprește la 120 m.",
      ru: "Однокомнатная квартира 42 м² на 7 этаже, с открытым видом на Долину Роз. Ремонт закончен в 2024 году, и с тех пор в квартире не жили — продаётся, потому что собственники уехали из страны. Для первой квартиры или под сдачу это одно из самых чистых предложений, что у нас есть в Ботанике.\n\nПланировка: прихожая, комната с зоной сна, отделённой стеллажом, кухня 8 м² открытая в гостиную, ванная с душевой, длинный застеклённый балкон.\n\nУдобства: центральное отопление с новыми радиаторами и термостатами, стеклопакеты, кухонная мебель на заказ, стиральная машина, холодильник и индукционная плита включены.\n\nВ доме: два рабочих лифта, домофон, двор с детской площадкой, обновлённой в 2025 году, и парковка без закрепления. Троллейбус в Центр останавливается в 120 м.",
    },
    landmark: { ro: "cu vedere spre Valea Trandafirilor", ru: "с видом на Долину Роз" },
    price: 74500,
    pricePerSqm: 1774,
    negotiable: false,
    rooms: 1,
    bedrooms: 1,
    bathrooms: 1,
    area: 42,
    livingArea: 24,
    kitchenArea: 8,
    floor: 7,
    floors: 9,
    ceilingHeight: 250,
    balconies: 1,
    sector: "botanica",
    street: "str. Nicolae Titulescu 8",
    coords: { lat: 46.9871, lng: 28.8642 },
    mapImage: MAP,
    poi: [
      poi("transport", "Stație troleibuz 17, 24", "Остановка троллейбуса 17, 24", 120),
      poi("parc", "Parcul Valea Trandafirilor", "Парк Долина Роз", 480),
      poi("magazin", "Nr.1", "Nr.1", 190),
      poi("policlinica", "Centrul medical Botanica", "Медцентр Ботаника", 640),
    ],
    fund: "fond-vechi",
    year: 1986,
    yearStatus: "finalizat",
    buildingType: "panou",
    condition: "euroreparatie",
    layout: "decomandat",
    heating: "centralizata",
    parking: "la-sol",
    amenities: [
      "balcon",
      "lift",
      "mobilat",
      "tehnica",
      "geamuri-termopan",
      "videointerfon",
      "teren-joaca",
      "internet",
    ],
    availableFrom: NOW,
    agentSlug: "natalia-rusu",
    photos: shots(
      ["apt-03", "apt-16", "apt-11", "apt-08", "block-06", "apt-12", "apt-20", "apt-05"],
      "str. Nicolae Titulescu 8"
    ),
    publishedAt: "2026-07-02",
    updatedAt: "2026-07-19",
    featured: false,
  },
  {
    id: "AR-1163",
    slug: "apartament-2-camere-alba-iulia-buiucani-ar-1163",
    deal: "vanzare",
    kind: "apartament",
    status: "activ",
    flags: ["comision-0"],
    title: {
      ro: "Apartament cu 2 camere în variantă albă, bd. Alba Iulia, Buiucani",
      ru: "2-комнатная квартира в белом варианте, бул. Алба-Юлия, Буюканы",
    },
    description: {
      ro: "Apartament în variantă albă într-un bloc dat în exploatare la începutul lui 2023, pe Alba Iulia. Se vinde direct de la primul proprietar, fără comision din partea cumpărătorului. Pereții sunt gletuiți, instalațiile trase, contoarele montate — mai rămâne finisajul, care la suprafața asta costă între 12 și 18 mii de euro, în funcție de materiale.\n\nCompartimentare: antreu, living cu bucătărie deschisă, dormitor separat, baie, balcon de 6 m² cu ieșire din living.\n\nFacilități: încălzire autonomă cu centrală montată și pusă în funcțiune, geamuri termopan din profil de cinci camere, ușă metalică de intrare, șapă turnată și nivelată.\n\nFacilitățile blocului: parcare subterană pe două niveluri (loc separat, 9 000 €), două lifturi, curte închisă fără mașini, videointerfon și supraveghere video pe tot perimetrul. Blocul are 12 etaje și e ocupat în proporție de aproximativ 70%.",
      ru: "Квартира в белом варианте в доме, сданном в начале 2023 года, на Алба-Юлия. Продаётся напрямую от первого собственника, без комиссии со стороны покупателя. Стены зашпаклёваны, коммуникации разведены, счётчики установлены — остаётся отделка, которая при такой площади обойдётся в 12-18 тысяч евро в зависимости от материалов.\n\nПланировка: прихожая, гостиная с открытой кухней, отдельная спальня, санузел, балкон 6 м² с выходом из гостиной.\n\nУдобства: автономное отопление с установленным и запущенным котлом, пятикамерные стеклопакеты, металлическая входная дверь, залитая и выровненная стяжка.\n\nВ доме: двухуровневый подземный паркинг (место отдельно, 9 000 €), два лифта, закрытый двор без машин, видеодомофон и видеонаблюдение по периметру. В доме 12 этажей, заселён примерно на 70%.",
    },
    price: 138000,
    pricePerSqm: 1944,
    negotiable: false,
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    area: 71,
    livingArea: 40,
    kitchenArea: 12,
    floor: 6,
    floors: 12,
    ceilingHeight: 270,
    balconies: 1,
    sector: "buiucani",
    street: "bd. Alba Iulia 91",
    coords: { lat: 47.0378, lng: 28.7796 },
    mapImage: MAP,
    poi: [
      poi("transport", "Stație troleibuz 3, 11", "Остановка троллейбуса 3, 11", 230),
      poi("magazin", "Kaufland Alba Iulia", "Kaufland Алба-Юлия", 550),
      poi("scoala", "Liceul Mircea Eliade", "Лицей Мирча Элиаде", 700),
      poi("gradinita", "Grădinița 199", "Детский сад 199", 340),
    ],
    fund: "bloc-nou",
    year: 2023,
    yearStatus: "finalizat",
    buildingType: "monolit",
    condition: "varianta-alba",
    layout: "decomandat",
    heating: "autonoma",
    parking: "subteran",
    amenities: [
      "parcare",
      "balcon",
      "lift",
      "centrala-termica",
      "geamuri-termopan",
      "videointerfon",
      "supraveghere-video",
      "curte-inchisa",
    ],
    developer: "Basconslux",
    complexSlug: "newton-house",
    availableFrom: NOW,
    agentSlug: "andrei-cebotari",
    photos: shots(
      ["apt-12", "apt-14", "block-02", "apt-06", "apt-19", "apt-17", "block-04", "apt-10"],
      "bd. Alba Iulia 91"
    ),
    publishedAt: "2026-06-14",
    updatedAt: "2026-07-17",
    featured: false,
  },
  {
    id: "AR-1171",
    slug: "apartament-3-camere-banulescu-bodoni-centru-ar-1171",
    deal: "vanzare",
    kind: "apartament",
    status: "activ",
    flags: ["gata-de-mutat"],
    title: {
      ro: "Apartament cu 3 camere, str. Bănulescu-Bodoni, Centru",
      ru: "3-комнатная квартира, ул. Бэнулеску-Бодони, Центр",
    },
    description: {
      ro: "Apartament cu proiect de design făcut de un birou din Chișinău și executat până la capăt, inclusiv mobilierul la comandă. Blocul e din 2021, are numai 24 de apartamente și o intrare cu recepție. De la etajul 8 se vede aproape tot Centrul, iar seara se aud mai degrabă copacii decât strada.\n\nCompartimentare: hol de intrare cu dressing, living deschis spre bucătărie și zona de luat masa, două dormitoare cu dressing propriu, două blocuri sanitare, cameră tehnică pentru spălat rufe, terasă de 9 m².\n\nFacilități: încălzire prin pardoseală în toate încăperile, recuperator de aer, climatizare pe canale, storuri electrice, bucătărie și dressinguri la comandă, tehnică Miele.\n\nFacilitățile blocului: parcare subterană cu două locuri incluse în preț, lift direct din parcare, generator pentru părțile comune, pază permanentă și curte interioară amenajată.",
      ru: "Квартира с дизайн-проектом от кишинёвского бюро, реализованным до конца, включая мебель на заказ. Дом 2021 года, всего 24 квартиры и вход с ресепшн. С 8 этажа виден почти весь Центр, а вечером слышны скорее деревья, чем улица.\n\nПланировка: холл с гардеробной, гостиная, открытая в кухню и обеденную зону, две спальни с собственными гардеробными, два санузла, техническое помещение для стирки, терраса 9 м².\n\nУдобства: тёплый пол во всех помещениях, рекуператор воздуха, канальное кондиционирование, электрические шторы, кухня и гардеробные на заказ, техника Miele.\n\nВ доме: подземный паркинг с двумя местами в цене, лифт прямо из паркинга, генератор для мест общего пользования, постоянная охрана и благоустроенный внутренний двор.",
    },
    landmark: { ro: "vizavi de Grădina Publică", ru: "напротив городского парка" },
    price: 218000,
    pricePerSqm: 2370,
    negotiable: true,
    rooms: 3,
    bedrooms: 2,
    bathrooms: 2,
    area: 92,
    livingArea: 58,
    kitchenArea: 14,
    floor: 8,
    floors: 10,
    ceilingHeight: 280,
    balconies: 1,
    sector: "centru",
    street: "str. Bănulescu-Bodoni 25",
    coords: { lat: 47.0233, lng: 28.8291 },
    mapImage: MAP,
    poi: [
      poi("transport", "Stație troleibuz 2, 3, 22", "Остановка троллейбуса 2, 3, 22", 160),
      poi("parc", "Grădina Publică Ștefan cel Mare", "Парк Штефана чел Маре", 210),
      poi("magazin", "Green Hills Market", "Green Hills Market", 280),
      poi("scoala", "Liceul Prometeu", "Лицей Прометеу", 520),
    ],
    fund: "bloc-nou",
    year: 2021,
    yearStatus: "finalizat",
    buildingType: "monolit",
    condition: "design-individual",
    layout: "decomandat",
    heating: "pardoseala",
    parking: "subteran",
    amenities: [
      "parcare",
      "terasa",
      "lift",
      "mobilat",
      "tehnica",
      "aer-conditionat",
      "incalzire-pardoseala",
      "videointerfon",
      "paza",
      "supraveghere-video",
      "curte-inchisa",
      "geamuri-termopan",
    ],
    developer: "Lagmar Impex",
    availableFrom: NOW,
    agentSlug: "andrei-cebotari",
    photos: shots(
      ["apt-10", "apt-06", "apt-15", "apt-04", "apt-17", "block-05", "apt-01", "apt-11", "apt-18", "apt-09"],
      "str. Bănulescu-Bodoni 25"
    ),
    publishedAt: "2026-07-05",
    updatedAt: "2026-07-25",
    featured: true,
  },
  {
    id: "AR-1184",
    slug: "apartament-2-camere-mircea-cel-batran-ciocana-ar-1184",
    deal: "vanzare",
    kind: "apartament",
    status: "activ",
    flags: [],
    title: {
      ro: "Apartament cu 2 camere, bd. Mircea cel Bătrân, Ciocana",
      ru: "2-комнатная квартира, бул. Мирча чел Бэтрын, Чеканы",
    },
    description: {
      ro: "Apartament la etajul 2 într-un bloc din 1991, seria care în Ciocana înseamnă bucătărie de 10 m² și camere separate. Reparație curată făcută în 2021: nimic spectaculos, dar nu ai ce reface în primii cinci ani. Curtea e largă, cu copaci mari și cu parcare care chiar ajunge.\n\nCompartimentare: antreu, două camere separate, bucătărie de 10 m², baie și WC separate, balcon și logie.\n\nFacilități: calorifere schimbate, geamuri termopan, instalație sanitară nouă, boiler, ușă metalică, chiuvetă și mobilă de bucătărie rămân.\n\nFacilitățile blocului: lift, subsol cu boxe, curte închisă cu barieră montată în 2024, teren de joacă și terenul de sport al liceului alături.",
      ru: "Квартира на 2 этаже в доме 1991 года — серия, которая в Чеканах означает кухню 10 м² и раздельные комнаты. Аккуратный ремонт 2021 года: ничего выдающегося, но переделывать в ближайшие пять лет нечего. Двор просторный, со взрослыми деревьями и парковкой, которой действительно хватает.\n\nПланировка: прихожая, две раздельные комнаты, кухня 10 м², раздельный санузел, балкон и лоджия.\n\nУдобства: заменённые радиаторы, стеклопакеты, новая сантехника, бойлер, металлическая дверь, мойка и кухонная мебель остаются.\n\nВ доме: лифт, подвал с кладовыми, закрытый двор со шлагбаумом, установленным в 2024 году, детская площадка и спортплощадка лицея рядом.",
    },
    price: 121500,
    pricePerSqm: 1898,
    negotiable: true,
    rooms: 2,
    bedrooms: 2,
    bathrooms: 1,
    area: 64,
    livingArea: 38,
    kitchenArea: 10,
    floor: 2,
    floors: 9,
    ceilingHeight: 255,
    balconies: 2,
    sector: "ciocana",
    street: "bd. Mircea cel Bătrân 17",
    coords: { lat: 47.0431, lng: 28.9047 },
    mapImage: MAP,
    poi: [
      poi("transport", "Stație troleibuz 15, 28", "Остановка троллейбуса 15, 28", 170),
      poi("scoala", "Liceul Ginta Latină", "Лицей Гинта Латинэ", 300),
      poi("magazin", "Linella", "Linella", 150),
      poi("parc", "Parcul Ciocana", "Парк Чеканы", 850),
    ],
    fund: "fond-vechi",
    year: 1991,
    yearStatus: "finalizat",
    buildingType: "panou",
    condition: "reparatie-cosmetica",
    layout: "decomandat",
    heating: "centralizata",
    parking: "la-sol",
    amenities: [
      "balcon",
      "lift",
      "geamuri-termopan",
      "pivnita",
      "bucatarie-separata",
      "curte-inchisa",
      "teren-joaca",
      "internet",
    ],
    availableFrom: NOW,
    agentSlug: "victor-morari",
    photos: shots(
      ["apt-14", "apt-03", "apt-05", "apt-08", "block-06", "apt-16", "apt-11", "apt-07"],
      "bd. Mircea cel Bătrân 17"
    ),
    publishedAt: "2026-06-21",
    updatedAt: "2026-07-15",
    featured: false,
  },
  {
    id: "AR-1190",
    slug: "apartament-1-camera-drumul-viilor-telecentru-ar-1190",
    deal: "vanzare",
    kind: "apartament",
    status: "activ",
    flags: [],
    title: {
      ro: "Apartament cu 1 cameră la parter, str. Drumul Viilor, Telecentru",
      ru: "1-комнатная квартира на первом этаже, ул. Друмул Виилор, Телецентр",
    },
    description: {
      ro: "Apartament la parter într-un bloc de cinci etaje din 1979, vândut așa cum e. Are nevoie de reparație completă — instalațiile sunt originale, iar bucătăria n-a fost schimbată niciodată. În schimb, prețul e sub orice altceva la suprafața asta în Telecentru, iar parterul înalt cu intrare separată posibilă face din el o variantă bună pentru un mic birou sau cabinet.\n\nCompartimentare: antreu, cameră de 18 m², bucătărie de 6 m², baie cu WC comun, cămară.\n\nFacilități: încălzire centralizată funcțională, contor de apă montat, geamuri de lemn originale, ușă de lemn. Curentul e tras pe siguranțe automate schimbate în 2018.\n\nFacilitățile blocului: curte liniștită cu copaci, subsol cu boxe, parcare pe stradă. Blocul nu are lift, dar apartamentul e la parter. Stația de troleibuz e la 90 m, iar șoseaua Hîncești la două minute pe jos.",
      ru: "Квартира на первом этаже пятиэтажного дома 1979 года, продаётся как есть. Требует полного ремонта — коммуникации родные, кухню никогда не меняли. Зато цена ниже всего остального при такой площади в Телецентре, а высокий первый этаж с возможностью отдельного входа делает её хорошим вариантом под небольшой офис или кабинет.\n\nПланировка: прихожая, комната 18 м², кухня 6 м², совмещённый санузел, кладовая.\n\nУдобства: центральное отопление в рабочем состоянии, счётчик воды установлен, родные деревянные окна, деревянная дверь. Электрика на автоматах, заменённых в 2018 году.\n\nВ доме: тихий двор с деревьями, подвал с кладовыми, парковка вдоль улицы. Лифта нет, но квартира на первом этаже. Остановка троллейбуса в 90 м, шоссе Хынчешть в двух минутах пешком.",
    },
    price: 70000,
    pricePerSqm: 1591,
    negotiable: true,
    rooms: 1,
    bedrooms: 1,
    bathrooms: 1,
    area: 44,
    livingArea: 18,
    kitchenArea: 6,
    floor: "parter",
    floors: 5,
    ceilingHeight: 250,
    balconies: 0,
    sector: "telecentru",
    street: "str. Drumul Viilor 34",
    coords: { lat: 47.0041, lng: 28.8062 },
    mapImage: MAP,
    poi: [
      poi("transport", "Stație troleibuz 12, 26", "Остановка троллейбуса 12, 26", 90),
      poi("magazin", "Local", "Local", 140),
      poi("scoala", "Liceul Ion Creangă", "Лицей Иона Крянгэ", 600),
      poi("policlinica", "Policlinica Telecentru", "Поликлиника Телецентр", 750),
    ],
    fund: "fond-vechi",
    year: 1979,
    yearStatus: "finalizat",
    buildingType: "caramida",
    condition: "necesita-reparatie",
    layout: "nedecomandat",
    heating: "centralizata",
    parking: "la-sol",
    amenities: ["pivnita", "bucatarie-separata"],
    availableFrom: NOW,
    agentSlug: "natalia-rusu",
    photos: shots(
      ["apt-07", "apt-08", "apt-03", "block-04", "apt-05", "apt-12", "apt-19", "apt-02"],
      "str. Drumul Viilor 34"
    ),
    publishedAt: "2026-06-11",
    updatedAt: "2026-07-12",
    featured: false,
  },
  {
    id: "AR-1203",
    slug: "apartament-4-camere-puskin-centru-ar-1203",
    deal: "vanzare",
    kind: "apartament",
    status: "activ",
    flags: ["exclusivitate"],
    title: {
      ro: "Apartament cu 4 camere, str. Pușkin, Centru",
      ru: "4-комнатная квартира, ул. Пушкина, Центр",
    },
    description: {
      ro: "Cel mai mare apartament din portofoliul nostru din Centru: 128 m² pe un singur nivel, la etajul 9 dintr-un bloc de 11, cu ferestre pe trei laturi. Proiectul de amenajare a fost gândit pentru o familie cu doi copii, cu zonele de zi și de noapte despărțite complet.\n\nCompartimentare: hol mare de intrare, living de 34 m², bucătărie separată cu ieșire pe balcon, trei dormitoare, două blocuri sanitare, cameră de serviciu, două balcoane.\n\nFacilități: încălzire autonomă, climatizare în fiecare cameră, parchet masiv de stejar, uși interioare din lemn masiv, bucătărie și dressinguri la comandă, storuri exterioare pe fațada de sud.\n\nFacilitățile blocului: două locuri de parcare subterană incluse, lift, pază permanentă la intrare, curte închisă cu acces pe cartelă. Blocul e din 2020 și are doar patru apartamente pe etaj.",
      ru: "Самая большая квартира в нашем портфеле в Центре: 128 м² на одном уровне, на 9 этаже 11-этажного дома, с окнами на три стороны. Планировочное решение делалось под семью с двумя детьми, дневная и ночная зоны разделены полностью.\n\nПланировка: большой входной холл, гостиная 34 м², отдельная кухня с выходом на балкон, три спальни, два санузла, подсобное помещение, два балкона.\n\nУдобства: автономное отопление, кондиционирование в каждой комнате, массивный дубовый паркет, межкомнатные двери из массива, кухня и гардеробные на заказ, внешние жалюзи на южном фасаде.\n\nВ доме: два места в подземном паркинге в цене, лифт, постоянная охрана на входе, закрытый двор с доступом по карте. Дом 2020 года, всего четыре квартиры на этаже.",
    },
    price: 298000,
    pricePerSqm: 2328,
    negotiable: true,
    rooms: 4,
    bedrooms: 3,
    bathrooms: 2,
    area: 128,
    livingArea: 84,
    kitchenArea: 15,
    floor: 9,
    floors: 11,
    ceilingHeight: 285,
    balconies: 2,
    sector: "centru",
    street: "str. Pușkin 47",
    coords: { lat: 47.0289, lng: 28.8318 },
    mapImage: MAP,
    poi: [
      poi("transport", "Stație troleibuz 1, 5, 8", "Остановка троллейбуса 1, 5, 8", 200),
      poi("scoala", "Liceul Gaudeamus", "Лицей Gaudeamus", 380),
      poi("magazin", "Green Hills Market", "Green Hills Market", 260),
      poi("parc", "Grădina Publică Ștefan cel Mare", "Парк Штефана чел Маре", 450),
    ],
    fund: "bloc-nou",
    year: 2020,
    yearStatus: "finalizat",
    buildingType: "monolit",
    condition: "design-individual",
    layout: "decomandat",
    heating: "autonoma",
    parking: "subteran",
    amenities: [
      "parcare",
      "balcon",
      "lift",
      "centrala-termica",
      "mobilat",
      "tehnica",
      "aer-conditionat",
      "videointerfon",
      "paza",
      "supraveghere-video",
      "curte-inchisa",
      "geamuri-termopan",
      "bucatarie-separata",
    ],
    developer: "Astercon Grup",
    availableFrom: NOW,
    agentSlug: "andrei-cebotari",
    photos: shots(
      ["apt-06", "apt-01", "apt-13", "apt-04", "apt-17", "apt-15", "block-01", "apt-11", "apt-18", "apt-05"],
      "str. Pușkin 47"
    ),
    publishedAt: "2026-06-30",
    updatedAt: "2026-07-26",
    featured: true,
  },
  {
    id: "AR-1215",
    slug: "apartament-2-camere-miron-costin-riscani-ar-1215",
    deal: "vanzare",
    kind: "apartament",
    status: "activ",
    flags: ["pret-redus"],
    title: {
      ro: "Apartament cu 2 camere, str. Miron Costin, Râșcani",
      ru: "2-комнатная квартира, ул. Мирона Костина, Рышкановка",
    },
    description: {
      ro: "Prețul a scăzut cu 7 000 € în iulie: proprietarul s-a mutat deja și vrea să închidă tranzacția până la sfârșitul verii. Apartamentul e la etajul 5 dintr-un bloc de 9 din 1983, cu euroreparație făcută în 2020 și întreținut bine de atunci.\n\nCompartimentare: antreu, living, dormitor, bucătărie de 9 m², baie cu cadă, logie de 6 m² închisă și izolată.\n\nFacilități: geamuri termopan, calorifere din aluminiu cu robinete termostatate, instalație electrică refăcută, boiler de 80 l, aer condiționat, mobilă de bucătărie și dulapuri încastrate rămân.\n\nFacilitățile blocului: lift schimbat în 2022, interfon, subsol cu boxă, curte cu parcare și teren de joacă. Piața Râșcani și stația de troleibuz sunt la 250 m.",
      ru: "Цена снижена на 7 000 € в июле: собственник уже переехал и хочет закрыть сделку до конца лета. Квартира на 5 этаже 9-этажного дома 1983 года, с евроремонтом 2020 года, с тех пор в хорошем состоянии.\n\nПланировка: прихожая, гостиная, спальня, кухня 9 м², ванная с ванной, лоджия 6 м² застеклена и утеплена.\n\nУдобства: стеклопакеты, алюминиевые радиаторы с термостатами, переделанная электрика, бойлер 80 л, кондиционер, кухонная мебель и встроенные шкафы остаются.\n\nВ доме: лифт заменён в 2022 году, домофон, подвал с кладовой, двор с парковкой и детской площадкой. Рынок Рышкановка и остановка троллейбуса в 250 м.",
    },
    price: 112000,
    previousPrice: 119000,
    pricePerSqm: 1697,
    negotiable: true,
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    area: 66,
    livingArea: 40,
    kitchenArea: 9,
    floor: 5,
    floors: 9,
    ceilingHeight: 250,
    balconies: 1,
    sector: "riscani",
    street: "str. Miron Costin 15",
    coords: { lat: 47.0554, lng: 28.8598 },
    mapImage: MAP,
    poi: [
      poi("transport", "Stație troleibuz 8, 13", "Остановка троллейбуса 8, 13", 250),
      poi("magazin", "Piața Râșcani", "Рынок Рышкановка", 260),
      poi("gradinita", "Grădinița 87", "Детский сад 87", 320),
      poi("parc", "Parcul Râșcani", "Парк Рышкановка", 900),
    ],
    fund: "fond-vechi",
    year: 1983,
    yearStatus: "finalizat",
    buildingType: "panou",
    condition: "euroreparatie",
    layout: "semidecomandat",
    heating: "centralizata",
    parking: "la-sol",
    amenities: [
      "balcon",
      "lift",
      "mobilat",
      "aer-conditionat",
      "geamuri-termopan",
      "videointerfon",
      "pivnita",
      "teren-joaca",
      "bucatarie-separata",
    ],
    availableFrom: NOW,
    agentSlug: "victor-morari",
    photos: shots(
      ["apt-09", "apt-02", "apt-11", "apt-08", "apt-12", "block-03", "apt-16", "apt-05"],
      "str. Miron Costin 15"
    ),
    publishedAt: "2026-05-29",
    updatedAt: "2026-07-22",
    featured: false,
  },
  {
    id: "AR-1228",
    slug: "apartament-3-camere-grenoble-botanica-ar-1228",
    deal: "vanzare",
    kind: "apartament",
    status: "activ",
    flags: [],
    title: {
      ro: "Apartament cu 3 camere, str. Grenoble, Botanica",
      ru: "3-комнатная квартира, ул. Гренобль, Ботаника",
    },
    description: {
      ro: "Apartament în variantă albă într-un bloc din 2019, în Grenoble Residence. Etajul 3 dintr-un bloc de 14, cu ferestre spre curtea interioară amenajată. Se vinde cu tot cu proiect de amenajare făcut de dezvoltator, dacă noul proprietar vrea să-l folosească.\n\nCompartimentare: antreu, living de 26 m², două dormitoare, bucătărie separată de 12 m², două blocuri sanitare, balcon de 5 m².\n\nFacilități: încălzire autonomă cu centrală montată, geamuri termopan, șapă turnată, tencuială mecanizată, instalații sanitare și electrice trase până la punct.\n\nFacilitățile blocului: parcare subterană și la sol, două lifturi, curte fără mașini cu teren de joacă și zonă de fitness în aer liber, videointerfon și supraveghere pe perimetru. Complexul e locuit complet, cu asociație de proprietari funcțională.",
      ru: "Квартира в белом варианте в доме 2019 года, в комплексе Grenoble Residence. 3 этаж 14-этажного дома, окна во благоустроенный внутренний двор. Продаётся вместе с дизайн-проектом от застройщика, если новый собственник захочет им воспользоваться.\n\nПланировка: прихожая, гостиная 26 м², две спальни, отдельная кухня 12 м², два санузла, балкон 5 м².\n\nУдобства: автономное отопление с установленным котлом, стеклопакеты, залитая стяжка, механизированная штукатурка, сантехника и электрика разведены до точек.\n\nВ доме: подземный и наземный паркинг, два лифта, двор без машин с детской площадкой и уличной зоной фитнеса, видеодомофон и видеонаблюдение по периметру. Комплекс полностью заселён, товарищество собственников работает.",
    },
    price: 129500,
    pricePerSqm: 1579,
    negotiable: true,
    rooms: 3,
    bedrooms: 2,
    bathrooms: 2,
    area: 82,
    livingArea: 50,
    kitchenArea: 12,
    floor: 3,
    floors: 14,
    ceilingHeight: 270,
    balconies: 1,
    sector: "botanica",
    street: "str. Grenoble 143",
    coords: { lat: 46.9798, lng: 28.8517 },
    mapImage: MAP,
    poi: [
      poi("transport", "Stație troleibuz 17, 30", "Остановка троллейбуса 17, 30", 190),
      poi("scoala", "Liceul Dante Alighieri", "Лицей Данте Алигьери", 520),
      poi("magazin", "Kaufland Botanica", "Kaufland Ботаника", 400),
      poi("parc", "Parcul Valea Trandafirilor", "Парк Долина Роз", 950),
    ],
    fund: "bloc-nou",
    year: 2019,
    yearStatus: "finalizat",
    buildingType: "monolit",
    condition: "varianta-alba",
    layout: "decomandat",
    heating: "autonoma",
    parking: "subteran",
    amenities: [
      "parcare",
      "balcon",
      "lift",
      "centrala-termica",
      "geamuri-termopan",
      "videointerfon",
      "supraveghere-video",
      "curte-inchisa",
      "teren-joaca",
      "bucatarie-separata",
    ],
    developer: "Dansicons",
    complexSlug: "grenoble-residence",
    availableFrom: NOW,
    agentSlug: "natalia-rusu",
    photos: shots(
      ["apt-13", "apt-12", "block-02", "apt-19", "apt-17", "apt-04", "apt-14", "block-06"],
      "str. Grenoble 143"
    ),
    publishedAt: "2026-06-18",
    updatedAt: "2026-07-16",
    featured: false,
  },
  {
    id: "AR-1236",
    slug: "apartament-2-camere-hincesti-telecentru-ar-1236",
    deal: "vanzare",
    kind: "apartament",
    status: "activ",
    flags: ["pret-redus", "gata-de-mutat"],
    title: {
      ro: "Apartament cu 2 camere, șos. Hîncești, Telecentru",
      ru: "2-комнатная квартира, шоссе Хынчешть, Телецентр",
    },
    description: {
      ro: "Bloc mic din 2018, doar 7 etaje și 28 de apartamente, la ieșirea spre Ialoveni. Apartamentul are euroreparație terminată în 2022 și e liber — se poate intra în ziua semnării. Prețul a fost redus în iulie pentru că proprietarii au cumpărat deja altceva.\n\nCompartimentare: antreu, living cu bucătărie deschisă, dormitor, baie, balcon de 5 m².\n\nFacilități: încălzire autonomă, geamuri termopan, parchet laminat de clasă 33, bucătărie la comandă cu tehnică încorporată, aer condiționat, ușă metalică.\n\nFacilitățile blocului: parcare la sol atribuită, lift, videointerfon, curte închisă. Stația de troleibuz e la 200 m, iar drumul până în Centru durează 12 minute în afara orelor de vârf.",
      ru: "Небольшой дом 2018 года, всего 7 этажей и 28 квартир, на выезде в сторону Яловен. В квартире евроремонт, законченный в 2022 году, и она свободна — заехать можно в день подписания. Цена снижена в июле, потому что собственники уже купили другое жильё.\n\nПланировка: прихожая, гостиная с открытой кухней, спальня, санузел, балкон 5 м².\n\nУдобства: автономное отопление, стеклопакеты, ламинат 33 класса, кухня на заказ со встроенной техникой, кондиционер, металлическая дверь.\n\nВ доме: закреплённое наземное парковочное место, лифт, видеодомофон, закрытый двор. Остановка троллейбуса в 200 м, дорога до Центра занимает 12 минут вне часа пик.",
    },
    price: 98000,
    previousPrice: 105000,
    pricePerSqm: 1581,
    negotiable: false,
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    area: 62,
    livingArea: 36,
    kitchenArea: 11,
    floor: 4,
    floors: 7,
    ceilingHeight: 265,
    balconies: 1,
    sector: "telecentru",
    street: "șos. Hîncești 62",
    coords: { lat: 46.9989, lng: 28.7958 },
    mapImage: MAP,
    poi: [
      poi("transport", "Stație troleibuz 12, 22", "Остановка троллейбуса 12, 22", 200),
      poi("magazin", "Linella", "Linella", 230),
      poi("gradinita", "Grădinița 145", "Детский сад 145", 410),
      poi("sala-sport", "Sala de sport Olimp", "Спортзал Olimp", 560),
    ],
    fund: "bloc-nou",
    year: 2018,
    yearStatus: "finalizat",
    buildingType: "monolit",
    condition: "euroreparatie",
    layout: "decomandat",
    heating: "autonoma",
    parking: "la-sol",
    amenities: [
      "parcare",
      "balcon",
      "lift",
      "centrala-termica",
      "mobilat",
      "tehnica",
      "aer-conditionat",
      "geamuri-termopan",
      "videointerfon",
      "curte-inchisa",
    ],
    availableFrom: NOW,
    agentSlug: "natalia-rusu",
    photos: shots(
      ["apt-11", "apt-20", "apt-18", "apt-08", "block-05", "apt-02", "apt-15", "apt-06"],
      "șos. Hîncești 62"
    ),
    publishedAt: "2026-06-05",
    updatedAt: "2026-07-23",
    featured: false,
  },
  {
    id: "AR-1247",
    slug: "apartament-1-camera-ion-creanga-buiucani-ar-1247",
    deal: "vanzare",
    kind: "apartament",
    status: "activ",
    flags: [],
    title: {
      ro: "Apartament cu 1 cameră, str. Ion Creangă, Buiucani",
      ru: "1-комнатная квартира, ул. Иона Крянгэ, Буюканы",
    },
    description: {
      ro: "Apartament de o cameră la etajul 6, într-o zonă din Buiucani unde blocurile stau printre copaci și traficul se oprește la ora 20. Reparație cosmetică făcută în 2019, curată și fără probleme, dar fără pretenții. Se vinde des la cumpărători care caută primul apartament sau o investiție pentru închiriat.\n\nCompartimentare: antreu, cameră de 19 m², bucătărie de 8 m², baie cu duș, balcon de 3 m² închis.\n\nFacilități: geamuri termopan, calorifere schimbate, boiler, mobilă de bucătărie și dulap în antreu rămân, internet prin fibră optică deja instalat.\n\nFacilitățile blocului: lift, interfon, subsol cu boxe, curte cu parcare neatribuită. Piața Buiucani și trei stații de transport public sunt în raza de 300 m.",
      ru: "Однокомнатная квартира на 6 этаже, в той части Буюкан, где дома стоят среди деревьев, а движение стихает к 20 часам. Косметический ремонт 2019 года, чистый и без проблем, но без претензий. Такие часто берут те, кто ищет первую квартиру или инвестицию под сдачу.\n\nПланировка: прихожая, комната 19 м², кухня 8 м², ванная с душевой, застеклённый балкон 3 м².\n\nУдобства: стеклопакеты, заменённые радиаторы, бойлер, кухонная мебель и шкаф в прихожей остаются, оптоволоконный интернет уже проведён.\n\nВ доме: лифт, домофон, подвал с кладовыми, двор с парковкой без закрепления. Рынок Буюканы и три остановки общественного транспорта в радиусе 300 м.",
    },
    price: 92000,
    pricePerSqm: 1957,
    negotiable: true,
    rooms: 1,
    bedrooms: 1,
    bathrooms: 1,
    area: 47,
    livingArea: 19,
    kitchenArea: 8,
    floor: 6,
    floors: 9,
    ceilingHeight: 250,
    balconies: 1,
    sector: "buiucani",
    street: "str. Ion Creangă 68",
    coords: { lat: 47.0344, lng: 28.7902 },
    mapImage: MAP,
    poi: [
      poi("transport", "Stație troleibuz 3, 25", "Остановка троллейбуса 3, 25", 160),
      poi("magazin", "Piața Buiucani", "Рынок Буюканы", 280),
      poi("scoala", "Liceul Ion Creangă", "Лицей Иона Крянгэ", 340),
      poi("parc", "Scuarul Buiucani", "Сквер Буюканы", 420),
    ],
    fund: "fond-vechi",
    year: 1988,
    yearStatus: "finalizat",
    buildingType: "panou",
    condition: "reparatie-cosmetica",
    layout: "decomandat",
    heating: "centralizata",
    parking: "la-sol",
    amenities: [
      "balcon",
      "lift",
      "mobilat",
      "geamuri-termopan",
      "videointerfon",
      "pivnita",
      "internet",
      "bucatarie-separata",
    ],
    availableFrom: NOW,
    agentSlug: "andrei-cebotari",
    photos: shots(
      ["apt-20", "apt-18", "apt-05", "apt-08", "block-06", "apt-14", "apt-03", "apt-16"],
      "str. Ion Creangă 68"
    ),
    publishedAt: "2026-07-01",
    updatedAt: "2026-07-18",
    featured: false,
  },
  {
    id: "AR-1259",
    slug: "apartament-3-camere-igor-vieru-ciocana-ar-1259",
    deal: "vanzare",
    kind: "apartament",
    status: "activ",
    flags: ["nou", "comision-0"],
    title: {
      ro: "Apartament cu 3 camere, str. Igor Vieru, Ciocana",
      ru: "3-комнатная квартира, ул. Игоря Виеру, Чеканы",
    },
    description: {
      ro: "Apartament în bloc dat în exploatare în primăvara lui 2024, în Eco City Residence. Se vinde direct de la dezvoltator, deci cumpărătorul nu plătește comision. Etajul 7 din 16, cu vedere spre zona verde dintre blocuri.\n\nCompartimentare: antreu, living cu bucătărie deschisă de 30 m², două dormitoare, două blocuri sanitare, balcon de 7 m² pe toată lungimea living-ului.\n\nFacilități: variantă albă cu tencuială mecanizată și șapă turnată, încălzire autonomă cu centrală montată, geamuri termopan din profil de șase camere, contoare individuale de apă, gaz și energie.\n\nFacilitățile blocului: parcare subterană pe două niveluri, trei lifturi, curte complet fără mașini cu teren de joacă, alei și iluminat propriu, videointerfon, supraveghere video și pază. Complexul are propria stație de transformare, deci nu depinde de rețeaua veche a sectorului.",
      ru: "Квартира в доме, сданном весной 2024 года, в комплексе Eco City Residence. Продаётся напрямую от застройщика, поэтому покупатель не платит комиссию. 7 этаж из 16, вид на зелёную зону между домами.\n\nПланировка: прихожая, гостиная с открытой кухней 30 м², две спальни, два санузла, балкон 7 м² во всю длину гостиной.\n\nУдобства: белый вариант с механизированной штукатуркой и залитой стяжкой, автономное отопление с установленным котлом, шестикамерные стеклопакеты, индивидуальные счётчики воды, газа и электроэнергии.\n\nВ доме: двухуровневый подземный паркинг, три лифта, полностью свободный от машин двор с детской площадкой, дорожками и собственным освещением, видеодомофон, видеонаблюдение и охрана. У комплекса своя трансформаторная подстанция, так что он не зависит от старых сетей сектора.",
    },
    price: 147500,
    pricePerSqm: 1867,
    negotiable: false,
    rooms: 3,
    bedrooms: 2,
    bathrooms: 2,
    area: 79,
    livingArea: 48,
    kitchenArea: 13,
    floor: 7,
    floors: 16,
    ceilingHeight: 280,
    balconies: 1,
    sector: "ciocana",
    street: "str. Igor Vieru 11",
    coords: { lat: 47.0459, lng: 28.9163 },
    mapImage: MAP,
    poi: [
      poi("transport", "Stație autobuz 23, 34", "Остановка автобуса 23, 34", 210),
      poi("gradinita", "Grădinița 216", "Детский сад 216", 180),
      poi("magazin", "Linella", "Linella", 240),
      poi("parc", "Parcul Ciocana", "Парк Чеканы", 600),
    ],
    fund: "bloc-nou",
    year: 2024,
    yearStatus: "finalizat",
    buildingType: "monolit",
    condition: "varianta-alba",
    layout: "decomandat",
    heating: "autonoma",
    parking: "subteran",
    amenities: [
      "parcare",
      "balcon",
      "lift",
      "centrala-termica",
      "geamuri-termopan",
      "videointerfon",
      "supraveghere-video",
      "paza",
      "curte-inchisa",
      "teren-joaca",
    ],
    developer: "Glorinal",
    complexSlug: "eco-city-residence",
    availableFrom: NOW,
    agentSlug: "victor-morari",
    photos: shots(
      ["apt-15", "apt-13", "block-01", "apt-12", "apt-19", "apt-17", "apt-06", "block-04", "apt-04"],
      "str. Igor Vieru 11"
    ),
    publishedAt: "2026-07-20",
    updatedAt: "2026-07-26",
    featured: true,
  },
  {
    id: "AR-1266",
    slug: "apartament-2-camere-petru-rares-posta-veche-ar-1266",
    deal: "vanzare",
    kind: "apartament",
    status: "activ",
    flags: ["nou"],
    title: {
      ro: "Apartament cu 2 camere, str. Petru Rareș, Poșta Veche",
      ru: "2-комнатная квартира, ул. Петру Рареша, Старая Почта",
    },
    description: {
      ro: "Apartament la etajul 3 dintr-un bloc de cinci etaje din 1992, într-o zonă în care nu trece niciun drum de tranzit. Euroreparația a fost făcută în 2021 de un constructor pentru propria familie, ceea ce se vede la detalii: prize suficiente, iluminat gândit, hidroizolație corectă în baie.\n\nCompartimentare: antreu, living, dormitor, bucătărie separată de 10 m², baie cu cadă, WC separat, balcon de 4 m² închis.\n\nFacilități: încălzire autonomă cu centrală pe gaz, geamuri termopan, tavane cu spoturi, parchet laminat, bucătărie la comandă cu tehnică încorporată, aer condiționat.\n\nFacilitățile blocului: intrare cu interfon, subsol uscat cu boxă, curte cu copaci mari și parcare care ajunge. Stația de troleibuz e la 260 m, iar magazinul și grădinița la mai puțin de 300 m.",
      ru: "Квартира на 3 этаже пятиэтажного дома 1992 года, в зоне, где нет ни одной транзитной дороги. Евроремонт сделан в 2021 году строителем для собственной семьи, и это видно по деталям: розеток достаточно, освещение продумано, гидроизоляция в ванной сделана правильно.\n\nПланировка: прихожая, гостиная, спальня, отдельная кухня 10 м², ванная с ванной, раздельный туалет, застеклённый балкон 4 м².\n\nУдобства: автономное отопление с газовым котлом, стеклопакеты, потолки со встроенными светильниками, ламинат, кухня на заказ со встроенной техникой, кондиционер.\n\nВ доме: подъезд с домофоном, сухой подвал с кладовой, двор со взрослыми деревьями и достаточной парковкой. Остановка троллейбуса в 260 м, магазин и детский сад менее чем в 300 м.",
    },
    price: 103500,
    pricePerSqm: 1784,
    negotiable: true,
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    area: 58,
    livingArea: 34,
    kitchenArea: 10,
    floor: 3,
    floors: 5,
    ceilingHeight: 255,
    balconies: 1,
    sector: "posta-veche",
    street: "str. Petru Rareș 29",
    coords: { lat: 47.0643, lng: 28.8502 },
    mapImage: MAP,
    poi: [
      poi("transport", "Stație troleibuz 14, 29", "Остановка троллейбуса 14, 29", 260),
      poi("gradinita", "Grădinița 108", "Детский сад 108", 290),
      poi("magazin", "Local", "Local", 180),
      poi("scoala", "Gimnaziul 53", "Гимназия 53", 520),
    ],
    fund: "fond-vechi",
    year: 1992,
    yearStatus: "finalizat",
    buildingType: "caramida",
    condition: "euroreparatie",
    layout: "decomandat",
    heating: "autonoma",
    parking: "la-sol",
    amenities: [
      "balcon",
      "centrala-termica",
      "mobilat",
      "tehnica",
      "aer-conditionat",
      "geamuri-termopan",
      "videointerfon",
      "pivnita",
      "bucatarie-separata",
    ],
    availableFrom: NOW,
    agentSlug: "victor-morari",
    photos: shots(
      ["apt-04", "apt-07", "apt-14", "apt-17", "block-03", "apt-09", "apt-11", "apt-01"],
      "str. Petru Rareș 29"
    ),
    publishedAt: "2026-07-22",
    updatedAt: "2026-07-26",
    featured: false,
  },
  {
    id: "AR-1274",
    slug: "casa-4-camere-durlesti-ar-1274",
    deal: "vanzare",
    kind: "casa",
    status: "activ",
    flags: ["gata-de-mutat"],
    title: {
      ro: "Casă cu 4 camere pe 6,5 ari, str. Cartușa, Durlești",
      ru: "Дом с 4 комнатами на 6,5 сотках, ул. Картуша, Дурлешты",
    },
    description: {
      ro: "Casă pe două niveluri terminată în 2021, la zece minute de Buiucani pe strada Cartușa. Construită de proprietari pentru ei, nu pentru vânzare — se vede în calitatea izolației și în faptul că factura de gaz iarna nu trece de 200 €. Curtea e amenajată complet, cu gazon, doi meri și o terasă acoperită în spate.\n\nCompartimentare: parter — antreu, bucătărie cu zonă de luat masa, living cu ieșire pe terasă, cameră de oaspeți, baie cu duș, cameră tehnică; etaj — trei dormitoare, baie mare, balcon.\n\nFacilități: încălzire autonomă cu centrală pe gaz și încălzire prin pardoseală la parter, geamuri termopan cu profil de șase camere, izolație de 10 cm pe fațadă, apă și canalizare centralizate, internet prin fibră.\n\nÎn curte: garaj pentru o mașină cu poartă automată, foișor, magazie, sistem de irigare, gard nou pe toate laturile. Terenul e de 6,5 ari, cu act de proprietate și cadastru făcute.",
      ru: "Двухуровневый дом, законченный в 2021 году, в десяти минутах от Буюкан по улице Картуша. Строили собственники для себя, а не на продажу — это видно по качеству утепления и по тому, что счёт за газ зимой не превышает 200 €. Двор полностью благоустроен: газон, две яблони и крытая терраса на задней стороне.\n\nПланировка: первый этаж — прихожая, кухня с обеденной зоной, гостиная с выходом на террасу, гостевая комната, ванная с душевой, техническое помещение; второй этаж — три спальни, большая ванная, балкон.\n\nУдобства: автономное отопление с газовым котлом и тёплым полом на первом этаже, шестикамерные стеклопакеты, 10 см утепления по фасаду, центральные вода и канализация, оптоволоконный интернет.\n\nВо дворе: гараж на одну машину с автоматическими воротами, беседка, сарай, система полива, новый забор по всему периметру. Участок 6,5 сотки, документы и кадастр оформлены.",
    },
    landmark: { ro: "la zece minute de Buiucani", ru: "в десяти минутах от Буюкан" },
    price: 219500,
    pricePerSqm: 1180,
    negotiable: true,
    rooms: 4,
    bedrooms: 3,
    bathrooms: 2,
    area: 186,
    livingArea: 118,
    kitchenArea: 18,
    landArea: 6.5,
    floor: 1,
    floors: 2,
    ceilingHeight: 280,
    balconies: 1,
    sector: "durlesti",
    street: "str. Cartușa 22",
    coords: { lat: 47.0294, lng: 28.7548 },
    mapImage: MAP,
    poi: [
      poi("transport", "Stație autobuz 30", "Остановка автобуса 30", 380),
      poi("scoala", "Liceul Durlești", "Лицей Дурлешты", 900),
      poi("magazin", "Fidesco", "Fidesco", 650),
      poi("gradinita", "Grădinița 3 Durlești", "Детский сад 3 Дурлешты", 720),
    ],
    fund: "bloc-nou",
    year: 2021,
    yearStatus: "finalizat",
    buildingType: "caramida",
    condition: "euroreparatie",
    heating: "autonoma",
    parking: "garaj",
    amenities: [
      "garaj",
      "terasa",
      "balcon",
      "centrala-termica",
      "gradina",
      "curte-inchisa",
      "geamuri-termopan",
      "incalzire-pardoseala",
      "internet",
      "bucatarie-separata",
    ],
    availableFrom: NOW,
    agentSlug: "victor-morari",
    photos: shots(
      ["house-01", "apt-01", "apt-15", "apt-04", "house-04", "apt-17", "apt-12", "apt-11", "apt-08"],
      "str. Cartușa 22, Durlești"
    ),
    publishedAt: "2026-06-25",
    updatedAt: "2026-07-20",
    featured: true,
  },
  {
    id: "AR-1281",
    slug: "casa-5-camere-stauceni-ar-1281",
    deal: "vanzare",
    kind: "casa",
    status: "activ",
    flags: ["exclusivitate"],
    title: {
      ro: "Casă cu 5 camere pe 8 ari, str. Alexandru cel Bun, Stăuceni",
      ru: "Дом с 5 комнатами на 8 сотках, ул. Александру чел Бун, Ставчены",
    },
    description: {
      ro: "Casă de 176 m² pe un teren de 8 ari, la marginea de sus a Stăucenilor, cu vedere spre vale. Construită în 2019 și locuită de atunci de o singură familie. Se vinde exclusiv prin ARCA, iar proprietarii acceptă vizionări și în weekend.\n\nCompartimentare: parter — antreu, bucătărie de 16 m², living de 32 m² cu șemineu, birou, baie cu duș; etaj — trei dormitoare, dintre care unul cu dressing, baie cu cadă, balcon peste toată lățimea casei.\n\nFacilități: încălzire autonomă cu centrală pe gaz și calorifere din oțel, șemineu pe lemne cu tubulatură spre etaj, geamuri termopan, izolație de 12 cm, boiler de 150 l, apă din rețeaua satului plus fântână proprie pentru grădină.\n\nÎn curte: parcare acoperită pentru două mașini, terasă de 24 m², grădină cu pomi fructiferi pe jumătate din teren, magazie de unelte, gard din piatră spre stradă. Drumul până în Râșcani durează 15 minute.",
      ru: "Дом 176 м² на участке 8 соток, в верхней части Ставчен, с видом на долину. Построен в 2019 году, с тех пор в нём жила одна семья. Продаётся эксклюзивно через ARCA, собственники принимают просмотры и в выходные.\n\nПланировка: первый этаж — прихожая, кухня 16 м², гостиная 32 м² с камином, кабинет, ванная с душевой; второй этаж — три спальни, одна из них с гардеробной, ванная с ванной, балкон во всю ширину дома.\n\nУдобства: автономное отопление с газовым котлом и стальными радиаторами, дровяной камин с разводкой на второй этаж, стеклопакеты, 12 см утепления, бойлер 150 л, вода из сельской сети плюс собственный колодец для сада.\n\nВо дворе: крытая парковка на две машины, терраса 24 м², сад с плодовыми деревьями на половине участка, сарай для инструмента, каменный забор со стороны улицы. Дорога до Рышкановки занимает 15 минут.",
    },
    landmark: { ro: "cu vedere spre vale", ru: "с видом на долину" },
    price: 198000,
    pricePerSqm: 1125,
    negotiable: true,
    rooms: 5,
    bedrooms: 3,
    bathrooms: 2,
    area: 176,
    livingArea: 108,
    kitchenArea: 16,
    landArea: 8,
    floor: 1,
    floors: 2,
    ceilingHeight: 275,
    balconies: 1,
    sector: "stauceni",
    street: "str. Alexandru cel Bun 14",
    coords: { lat: 47.0837, lng: 28.8721 },
    mapImage: MAP,
    poi: [
      poi("transport", "Stație autobuz 16", "Остановка автобуса 16", 450),
      poi("scoala", "Liceul Stăuceni", "Лицей Ставчены", 1100),
      poi("magazin", "Local Stăuceni", "Local Ставчены", 520),
      poi("parc", "Zona verde Stăuceni", "Зелёная зона Ставчены", 300),
    ],
    fund: "bloc-nou",
    year: 2019,
    yearStatus: "finalizat",
    buildingType: "caramida",
    condition: "euroreparatie",
    heating: "autonoma",
    parking: "la-sol",
    amenities: [
      "parcare",
      "terasa",
      "balcon",
      "centrala-termica",
      "gradina",
      "curte-inchisa",
      "geamuri-termopan",
      "pivnita",
      "bucatarie-separata",
      "internet",
    ],
    availableFrom: NOW,
    agentSlug: "natalia-rusu",
    photos: shots(
      ["house-02", "apt-13", "apt-09", "apt-05", "house-03", "apt-18", "apt-17", "apt-11"],
      "str. Alexandru cel Bun 14, Stăuceni"
    ),
    publishedAt: "2026-06-08",
    updatedAt: "2026-07-14",
    featured: true,
  },
  {
    id: "AR-1295",
    slug: "casa-4-camere-codru-ar-1295",
    deal: "vanzare",
    kind: "casa",
    status: "activ",
    flags: [],
    title: {
      ro: "Casă cu 4 camere pe 5,8 ari, str. Sihastrului, Codru",
      ru: "Дом с 4 комнатами на 5,8 сотках, ул. Сихаструлуй, Кодру",
    },
    description: {
      ro: "Casă în Codru, pe o stradă care se termină în pădure. Construită în 2016, cu un proiect de arhitect și finisaje alese de proprietar: piatră naturală pe fațadă, lemn masiv la interior, ferestre mari spre sud. E genul de casă care se vinde repede pentru că nu mai trebuie făcut nimic la ea.\n\nCompartimentare: parter — hol, bucătărie deschisă spre living de 38 m², cămară, baie cu duș, cameră tehnică; etaj — trei dormitoare, baie cu cadă și fereastră, terasă de 12 m².\n\nFacilități: încălzire prin pardoseală la parter și calorifere la etaj, pompă de căldură plus centrală pe gaz ca rezervă, recuperator de aer, geamuri termopan cu triplu sticlă, panouri fotovoltaice de 5 kW montate în 2023.\n\nÎn curte: parcare pentru două mașini sub copertină, terasă de lemn, grădină mică cu sistem de picurare, gard din lemn și metal. Pădurea Codrilor începe la 200 m de poartă.",
      ru: "Дом в Кодру, на улице, которая упирается в лес. Построен в 2016 году по архитектурному проекту, отделка выбрана собственником: натуральный камень на фасаде, массив дерева внутри, большие окна на юг. Это тот дом, который продаётся быстро, потому что делать в нём уже ничего не нужно.\n\nПланировка: первый этаж — холл, кухня, открытая в гостиную 38 м², кладовая, ванная с душевой, техническое помещение; второй этаж — три спальни, ванная с ванной и окном, терраса 12 м².\n\nУдобства: тёплый пол на первом этаже и радиаторы на втором, тепловой насос плюс газовый котёл как резерв, рекуператор воздуха, трёхкамерные стеклопакеты, солнечные панели 5 кВт, установленные в 2023 году.\n\nВо дворе: парковка на две машины под навесом, деревянная терраса, небольшой сад с капельным поливом, забор из дерева и металла. Кодринский лес начинается в 200 м от ворот.",
    },
    landmark: { ro: "la 200 m de pădure", ru: "в 200 м от леса" },
    price: 201500,
    pricePerSqm: 1308,
    negotiable: false,
    rooms: 4,
    bedrooms: 3,
    bathrooms: 2,
    area: 154,
    livingArea: 96,
    kitchenArea: 14,
    landArea: 5.8,
    floor: 1,
    floors: 2,
    ceilingHeight: 285,
    balconies: 0,
    sector: "codru",
    street: "str. Sihastrului 9",
    coords: { lat: 46.9877, lng: 28.7941 },
    mapImage: MAP,
    poi: [
      poi("transport", "Stație autobuz 11", "Остановка автобуса 11", 520),
      poi("parc", "Pădurea Codrilor", "Кодринский лес", 200),
      poi("magazin", "Fidesco Codru", "Fidesco Кодру", 850),
      poi("scoala", "Liceul Codru", "Лицей Кодру", 1300),
    ],
    fund: "bloc-nou",
    year: 2016,
    yearStatus: "finalizat",
    buildingType: "caramida",
    condition: "design-individual",
    heating: "pardoseala",
    parking: "la-sol",
    amenities: [
      "parcare",
      "terasa",
      "centrala-termica",
      "gradina",
      "curte-inchisa",
      "geamuri-termopan",
      "incalzire-pardoseala",
      "aer-conditionat",
      "internet",
    ],
    availableFrom: { ro: "Septembrie 2026", ru: "Сентябрь 2026" },
    agentSlug: "andrei-cebotari",
    photos: shots(
      ["house-03", "apt-06", "apt-10", "apt-15", "house-04", "apt-04", "apt-17", "apt-12"],
      "str. Sihastrului 9, Codru"
    ),
    publishedAt: "2026-07-07",
    updatedAt: "2026-07-24",
    featured: false,
  },
  {
    id: "AR-1302",
    slug: "spatiu-comercial-stefan-cel-mare-centru-ar-1302",
    deal: "vanzare",
    kind: "comercial",
    status: "activ",
    flags: ["exclusivitate"],
    title: {
      ro: "Spațiu comercial 118 m² la stradă, bd. Ștefan cel Mare, Centru",
      ru: "Коммерческое помещение 118 м² на первой линии, бул. Штефан чел Маре, Центр",
    },
    description: {
      ro: "Spațiu comercial la parterul unei clădiri din 1968, direct pe bulevardul Ștefan cel Mare, cu vitrină de 9 metri spre trotuar. Are intrare separată de la stradă și a funcționat ultimii opt ani ca showroom. Traficul pietonal pe segmentul ăsta e printre cele mai mari din oraș.\n\nCompartimentare: sală principală de 74 m² fără stâlpi, două încăperi de birou, depozit, grup sanitar, intrare tehnică din curtea interioară.\n\nFacilități: putere electrică instalată de 25 kW, climatizare pe canale, gresie și tavan tehnic, alarmă și supraveghere video montate, geamuri de vitrină cu folie de protecție.\n\nDestinația e comercială în acte, cu toate autorizațiile pe loc. Se poate cumpăra cu chiriașul actual, care are contract până în martie 2027 la 2 100 € pe lună — adică o randare brută de aproximativ 13% pe an la prețul cerut.",
      ru: "Коммерческое помещение на первом этаже здания 1968 года, прямо на бульваре Штефан чел Маре, с витриной 9 метров на тротуар. Отдельный вход с улицы, последние восемь лет работало как шоурум. Пешеходный трафик на этом отрезке — один из самых высоких в городе.\n\nПланировка: основной зал 74 м² без колонн, два офисных помещения, склад, санузел, технический вход со внутреннего двора.\n\nУдобства: установленная электрическая мощность 25 кВт, канальное кондиционирование, керамогранит и технический потолок, сигнализация и видеонаблюдение установлены, витринные стёкла с защитной плёнкой.\n\nНазначение по документам коммерческое, все разрешения на месте. Можно купить с действующим арендатором, у которого договор до марта 2027 года на 2 100 € в месяц — то есть валовая доходность около 13% годовых к запрашиваемой цене.",
    },
    price: 190000,
    pricePerSqm: 1610,
    negotiable: true,
    rooms: 0,
    bathrooms: 1,
    area: 118,
    floor: "parter",
    floors: 5,
    ceilingHeight: 320,
    balconies: 0,
    sector: "centru",
    street: "bd. Ștefan cel Mare 78",
    coords: { lat: 47.0251, lng: 28.8345 },
    mapImage: MAP,
    poi: [
      poi("transport", "Stație troleibuz 1, 3, 5, 8", "Остановка троллейбуса 1, 3, 5, 8", 80),
      poi("magazin", "Unic", "Unic", 220),
      poi("parc", "Grădina Publică Ștefan cel Mare", "Парк Штефана чел Маре", 350),
      poi("policlinica", "Centrul medical Ștefan cel Mare", "Медцентр Штефан чел Маре", 480),
    ],
    fund: "fond-vechi",
    year: 1968,
    yearStatus: "finalizat",
    buildingType: "caramida",
    condition: "euroreparatie",
    heating: "centralizata",
    parking: "la-sol",
    amenities: [
      "aer-conditionat",
      "supraveghere-video",
      "paza",
      "geamuri-termopan",
      "internet",
      "pivnita",
    ],
    availableFrom: { ro: "Martie 2027", ru: "Март 2027" },
    agentSlug: "andrei-cebotari",
    photos: shots(
      ["office", "block-03", "apt-19", "apt-10", "block-05", "apt-14", "apt-17", "block-01"],
      "bd. Ștefan cel Mare 78"
    ),
    publishedAt: "2026-06-16",
    updatedAt: "2026-07-19",
    featured: false,
  },
  {
    id: "AR-1311",
    slug: "birou-86-mp-vlaicu-parcalab-centru-ar-1311",
    deal: "vanzare",
    kind: "birou",
    status: "activ",
    flags: [],
    title: {
      ro: "Birou 86 m² într-un centru de afaceri, str. Vlaicu Pârcălab, Centru",
      ru: "Офис 86 м² в бизнес-центре, ул. Влайку Пыркэлаб, Центр",
    },
    description: {
      ro: "Birou la etajul 4 al unui centru de afaceri din 2008, la două minute de Ștefan cel Mare. Se vinde mobilat, cu tot cu birouri, scaune și sala de ședințe — proprietarul își mută echipa în alt oraș.\n\nCompartimentare: open space pentru 10-12 locuri de muncă, cabinet separat, sală de ședințe pentru 8 persoane, bucătărie de serviciu, grup sanitar propriu.\n\nFacilități: climatizare individuală pe fiecare zonă, cablare structurată Cat 6 la fiecare post, două linii de internet de la furnizori diferiți, jaluzele verticale, mochetă comercială schimbată în 2024.\n\nFacilitățile clădirii: recepție la parter, lift, parcare cu barieră (două locuri incluse), pază 24/24, generator pentru părțile comune. Cheltuielile comune sunt de 1,8 €/m² pe lună.",
      ru: "Офис на 4 этаже бизнес-центра 2008 года, в двух минутах от Штефана чел Маре. Продаётся с мебелью, включая столы, кресла и переговорную — собственник переводит команду в другой город.\n\nПланировка: open space на 10-12 рабочих мест, отдельный кабинет, переговорная на 8 человек, служебная кухня, собственный санузел.\n\nУдобства: индивидуальное кондиционирование по зонам, структурированная кабельная сеть Cat 6 на каждое место, две линии интернета от разных провайдеров, вертикальные жалюзи, коммерческий ковролин заменён в 2024 году.\n\nВ здании: ресепшн на первом этаже, лифт, парковка со шлагбаумом (два места включены), охрана 24/7, генератор для мест общего пользования. Коммунальные расходы 1,8 €/м² в месяц.",
    },
    price: 124500,
    pricePerSqm: 1448,
    negotiable: true,
    rooms: 0,
    bathrooms: 1,
    area: 86,
    floor: 4,
    floors: 6,
    ceilingHeight: 290,
    balconies: 0,
    sector: "centru",
    street: "str. Vlaicu Pârcălab 63",
    coords: { lat: 47.0273, lng: 28.8302 },
    mapImage: MAP,
    poi: [
      poi("transport", "Stație troleibuz 4, 22", "Остановка троллейбуса 4, 22", 150),
      poi("magazin", "Green Hills Market", "Green Hills Market", 300),
      poi("parc", "Grădina Publică Ștefan cel Mare", "Парк Штефана чел Маре", 420),
      poi("sala-sport", "World Class Chișinău", "World Class Кишинёв", 560),
    ],
    fund: "bloc-nou",
    year: 2008,
    yearStatus: "finalizat",
    buildingType: "monolit",
    condition: "euroreparatie",
    heating: "centralizata",
    parking: "la-sol",
    amenities: [
      "parcare",
      "lift",
      "mobilat",
      "aer-conditionat",
      "paza",
      "supraveghere-video",
      "geamuri-termopan",
      "internet",
    ],
    availableFrom: NOW,
    agentSlug: "andrei-cebotari",
    photos: shots(
      ["apt-19", "office", "block-02", "apt-14", "apt-10", "block-04", "apt-17", "apt-06"],
      "str. Vlaicu Pârcălab 63"
    ),
    publishedAt: "2026-06-02",
    updatedAt: "2026-07-11",
    featured: false,
  },
  {
    id: "AR-1338",
    slug: "chirie-apartament-2-camere-armeneasca-centru-ar-1338",
    deal: "chirie",
    kind: "apartament",
    status: "activ",
    flags: ["gata-de-mutat"],
    title: {
      ro: "Chirie apartament cu 2 camere, str. Armenească, Centru",
      ru: "Аренда 2-комнатной квартиры, ул. Армянская, Центр",
    },
    description: {
      ro: "Apartament complet mobilat și utilat, într-un bloc din 2019 pe Armenească. Se închiriază pe termen lung, minimum un an, preferabil unei familii sau unui cuplu care lucrează în Centru. Proprietarul stă în altă țară, iar administrarea o facem noi — reparațiile se rezolvă în 48 de ore.\n\nCompartimentare: antreu, living cu bucătărie deschisă, dormitor separat, baie cu duș, balcon de 5 m² cu vedere spre curte.\n\nFacilități: încălzire autonomă, aer condiționat, mașină de spălat, mașină de spălat vase, cuptor și plită cu inducție, frigider, televizor, pat de 160 cm cu saltea nouă, internet inclus în chirie.\n\nCondiții: chiria e de 950 € pe lună, plus cheltuieli (aproximativ 90-140 € iarna, 40-60 € vara). Garanție de o lună. Fără animale. Locul de parcare subterană se poate închiria separat, cu 60 € pe lună.",
      ru: "Полностью меблированная и укомплектованная квартира в доме 2019 года на Армянской. Сдаётся на длительный срок, минимум на год, желательно семье или паре, работающей в Центре. Собственник живёт за границей, управление ведём мы — ремонтные вопросы решаются в течение 48 часов.\n\nПланировка: прихожая, гостиная с открытой кухней, отдельная спальня, ванная с душевой, балкон 5 м² с видом во двор.\n\nУдобства: автономное отопление, кондиционер, стиральная и посудомоечная машины, духовка и индукционная плита, холодильник, телевизор, кровать 160 см с новым матрасом, интернет включён в аренду.\n\nУсловия: аренда 950 € в месяц плюс коммунальные (примерно 90-140 € зимой, 40-60 € летом). Залог за один месяц. Без животных. Место в подземном паркинге можно арендовать отдельно за 60 € в месяц.",
    },
    price: 950,
    pricePerSqm: 15,
    negotiable: false,
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    area: 64,
    livingArea: 38,
    kitchenArea: 11,
    floor: 5,
    floors: 9,
    ceilingHeight: 270,
    balconies: 1,
    sector: "centru",
    street: "str. Armenească 34",
    coords: { lat: 47.0219, lng: 28.8383 },
    mapImage: MAP,
    poi: [
      poi("transport", "Stație troleibuz 3, 22", "Остановка троллейбуса 3, 22", 140),
      poi("magazin", "Linella", "Linella", 170),
      poi("parc", "Grădina Publică Ștefan cel Mare", "Парк Штефана чел Маре", 700),
      poi("sala-sport", "Fitness Zone", "Fitness Zone", 390),
    ],
    fund: "bloc-nou",
    year: 2019,
    yearStatus: "finalizat",
    buildingType: "monolit",
    condition: "euroreparatie",
    layout: "decomandat",
    heating: "autonoma",
    parking: "subteran",
    amenities: [
      "parcare",
      "balcon",
      "lift",
      "centrala-termica",
      "mobilat",
      "tehnica",
      "aer-conditionat",
      "geamuri-termopan",
      "videointerfon",
      "curte-inchisa",
      "internet",
    ],
    availableFrom: NOW,
    agentSlug: "cristina-lungu",
    photos: shots(
      ["apt-05", "apt-16", "apt-18", "apt-08", "block-02", "apt-11", "apt-02", "apt-12"],
      "str. Armenească 34"
    ),
    publishedAt: "2026-07-13",
    updatedAt: "2026-07-25",
    featured: false,
  },
  {
    id: "AR-1345",
    slug: "chirie-apartament-1-camera-trandafirilor-botanica-ar-1345",
    deal: "chirie",
    kind: "apartament",
    status: "activ",
    flags: [],
    title: {
      ro: "Chirie apartament cu 1 cameră, str. Trandafirilor, Botanica",
      ru: "Аренда 1-комнатной квартиры, ул. Трандафирилор, Ботаника",
    },
    description: {
      ro: "Garsonieră mobilată în Botanica, la 400 m de parcul Valea Trandafirilor. Apartamentul e într-un bloc din 1985, cu reparație cosmetică refăcută anul trecut. Se închiriază pe termen lung, iar proprietara acceptă studenți și persoane care lucrează în ture.\n\nCompartimentare: antreu, cameră de 20 m² cu canapea extensibilă și birou, bucătărie separată de 8 m², baie cu cadă, balcon închis.\n\nFacilități: mobilă completă, frigider, mașină de spălat, cuptor cu microunde, aragaz, televizor, geamuri termopan, internet prin fibră inclus.\n\nCondiții: 550 € pe lună plus cheltuieli (60-110 € iarna, 25-40 € vara). Garanție de o lună. Animalele mici se acceptă cu acordul proprietarei. Se poate intra de la 1 august.",
      ru: "Меблированная однокомнатная квартира в Ботанике, в 400 м от парка Долина Роз. Дом 1985 года, косметический ремонт обновлён в прошлом году. Сдаётся на длительный срок, собственница принимает студентов и людей, работающих по сменам.\n\nПланировка: прихожая, комната 20 м² с раскладным диваном и письменным столом, отдельная кухня 8 м², ванная с ванной, застеклённый балкон.\n\nУдобства: полная меблировка, холодильник, стиральная машина, микроволновая печь, газовая плита, телевизор, стеклопакеты, оптоволоконный интернет включён.\n\nУсловия: 550 € в месяц плюс коммунальные (60-110 € зимой, 25-40 € летом). Залог за один месяц. Небольшие животные — по согласованию с собственницей. Заселение возможно с 1 августа.",
    },
    price: 550,
    pricePerSqm: 13,
    negotiable: false,
    rooms: 1,
    bedrooms: 1,
    bathrooms: 1,
    area: 44,
    livingArea: 20,
    kitchenArea: 8,
    floor: 3,
    floors: 5,
    ceilingHeight: 250,
    balconies: 1,
    sector: "botanica",
    street: "str. Trandafirilor 21",
    coords: { lat: 46.9814, lng: 28.8669 },
    mapImage: MAP,
    poi: [
      poi("transport", "Stație troleibuz 17, 24", "Остановка троллейбуса 17, 24", 180),
      poi("parc", "Parcul Valea Trandafirilor", "Парк Долина Роз", 400),
      poi("magazin", "Linella", "Linella", 130),
      poi("policlinica", "Policlinica Botanica", "Поликлиника Ботаника", 700),
    ],
    fund: "fond-vechi",
    year: 1985,
    yearStatus: "finalizat",
    buildingType: "panou",
    condition: "reparatie-cosmetica",
    layout: "decomandat",
    heating: "centralizata",
    parking: "la-sol",
    amenities: [
      "balcon",
      "lift",
      "mobilat",
      "tehnica",
      "geamuri-termopan",
      "internet",
      "bucatarie-separata",
    ],
    availableFrom: { ro: "1 august 2026", ru: "1 августа 2026" },
    agentSlug: "cristina-lungu",
    photos: shots(
      ["apt-18", "apt-20", "apt-11", "apt-08", "block-06", "apt-03", "apt-14", "apt-05"],
      "str. Trandafirilor 21"
    ),
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-24",
    featured: false,
  },
  {
    id: "AR-1352",
    slug: "chirie-apartament-3-camere-alba-iulia-buiucani-ar-1352",
    deal: "chirie",
    kind: "apartament",
    status: "activ",
    flags: ["comision-0", "gata-de-mutat"],
    title: {
      ro: "Chirie apartament cu 3 camere, bd. Alba Iulia, Buiucani",
      ru: "Аренда 3-комнатной квартиры, бул. Алба-Юлия, Буюканы",
    },
    description: {
      ro: "Apartament cu trei camere într-un bloc din 2017, la etajul 8, cu vedere spre Calea Ieșilor. Complet mobilat și utilat, potrivit pentru o familie cu copii — sunt două grădinițe și un liceu în raza de 500 m. Se închiriază fără comision, pentru că administrăm apartamentul de doi ani.\n\nCompartimentare: antreu, living de 24 m², două dormitoare, bucătărie separată de 12 m², două blocuri sanitare, balcon lung cu ieșire din living.\n\nFacilități: încălzire autonomă, aer condiționat în living și în dormitorul mare, mobilă completă, mașină de spălat, mașină de spălat vase, cuptor electric, plită cu inducție, frigider mare, două televizoare, internet inclus.\n\nCondiții: 850 € pe lună, garanție de o lună, contract pe minimum un an. Cheltuielile comune sunt de aproximativ 45 € pe lună, iar gazul și curentul se plătesc separat. Locul de parcare subterană e inclus în chirie.",
      ru: "Трёхкомнатная квартира в доме 2017 года, на 8 этаже, с видом на Каля Ешилор. Полностью меблирована и укомплектована, подходит семье с детьми — два детских сада и лицей в радиусе 500 м. Сдаётся без комиссии, потому что мы управляем этой квартирой уже два года.\n\nПланировка: прихожая, гостиная 24 м², две спальни, отдельная кухня 12 м², два санузла, длинный балкон с выходом из гостиной.\n\nУдобства: автономное отопление, кондиционеры в гостиной и большой спальне, полная меблировка, стиральная и посудомоечная машины, электрическая духовка, индукционная плита, большой холодильник, два телевизора, интернет включён.\n\nУсловия: 850 € в месяц, залог за один месяц, договор минимум на год. Общедомовые расходы около 45 € в месяц, газ и электричество оплачиваются отдельно. Место в подземном паркинге включено в аренду.",
    },
    price: 850,
    pricePerSqm: 10,
    negotiable: false,
    rooms: 3,
    bedrooms: 2,
    bathrooms: 2,
    area: 84,
    livingArea: 52,
    kitchenArea: 12,
    floor: 8,
    floors: 14,
    ceilingHeight: 270,
    balconies: 1,
    sector: "buiucani",
    street: "bd. Alba Iulia 190",
    coords: { lat: 47.0405, lng: 28.7714 },
    mapImage: MAP,
    poi: [
      poi("transport", "Stație troleibuz 11, 25", "Остановка троллейбуса 11, 25", 190),
      poi("gradinita", "Grădinița 183", "Детский сад 183", 250),
      poi("scoala", "Liceul Mircea Eliade", "Лицей Мирча Элиаде", 480),
      poi("magazin", "Kaufland Alba Iulia", "Kaufland Алба-Юлия", 350),
    ],
    fund: "bloc-nou",
    year: 2017,
    yearStatus: "finalizat",
    buildingType: "monolit",
    condition: "euroreparatie",
    layout: "decomandat",
    heating: "autonoma",
    parking: "subteran",
    amenities: [
      "parcare",
      "balcon",
      "lift",
      "centrala-termica",
      "mobilat",
      "tehnica",
      "aer-conditionat",
      "geamuri-termopan",
      "videointerfon",
      "curte-inchisa",
      "teren-joaca",
      "internet",
    ],
    availableFrom: NOW,
    agentSlug: "cristina-lungu",
    photos: shots(
      ["apt-16", "apt-01", "apt-04", "apt-12", "apt-17", "block-01", "apt-09", "apt-05", "apt-19"],
      "bd. Alba Iulia 190"
    ),
    publishedAt: "2026-07-11",
    updatedAt: "2026-07-23",
    featured: false,
  },
  {
    id: "AR-1361",
    slug: "chirie-apartament-2-camere-renasterii-riscani-ar-1361",
    deal: "chirie",
    kind: "apartament",
    status: "activ",
    flags: ["nou"],
    title: {
      ro: "Chirie apartament cu 2 camere, bd. Renașterii Naționale, Râșcani",
      ru: "Аренда 2-комнатной квартиры, бул. Ренаштерий Национале, Рышкановка",
    },
    description: {
      ro: "Apartament cu proiect de design, într-un bloc din 2021 din complexul Favorit Residence. E prima dată când se închiriază — proprietarii l-au folosit până acum ei. Mobilierul e la comandă, iar baia are finisaj din marmură naturală.\n\nCompartimentare: antreu cu dressing, living cu bucătărie deschisă, dormitor separat, baie cu cadă și fereastră, balcon de 6 m².\n\nFacilități: încălzire prin pardoseală, aer condiționat, mobilă la comandă în toate camerele, tehnică Bosch încorporată, mașină de spălat și uscător, storuri electrice, internet prin fibră inclus.\n\nCondiții: 900 € pe lună, garanție de o lună, contract pe minimum un an. Loc de parcare subterană inclus. Fără animale și fără fumat în apartament. Se poate vedea în orice zi, inclusiv sâmbăta.",
      ru: "Квартира с дизайн-проектом в доме 2021 года в комплексе Favorit Residence. Сдаётся впервые — до сих пор собственники жили в ней сами. Мебель на заказ, ванная отделана натуральным мрамором.\n\nПланировка: прихожая с гардеробной, гостиная с открытой кухней, отдельная спальня, ванная с ванной и окном, балкон 6 м².\n\nУдобства: тёплый пол, кондиционер, мебель на заказ во всех комнатах, встроенная техника Bosch, стиральная машина и сушка, электрические шторы, оптоволоконный интернет включён.\n\nУсловия: 900 € в месяц, залог за один месяц, договор минимум на год. Место в подземном паркинге включено. Без животных и без курения в квартире. Посмотреть можно в любой день, включая субботу.",
    },
    price: 900,
    pricePerSqm: 13,
    negotiable: false,
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    area: 70,
    livingArea: 42,
    kitchenArea: 12,
    floor: 6,
    floors: 10,
    ceilingHeight: 275,
    balconies: 1,
    sector: "riscani",
    street: "bd. Renașterii Naționale 12",
    coords: { lat: 47.0471, lng: 28.8607 },
    mapImage: MAP,
    poi: [
      poi("transport", "Stație troleibuz 8, 13, 29", "Остановка троллейбуса 8, 13, 29", 160),
      poi("parc", "Parcul Râșcani", "Парк Рышкановка", 450),
      poi("magazin", "Green Hills Market", "Green Hills Market", 220),
      poi("sala-sport", "Sala de sport Renașterea", "Спортзал Ренаштеря", 380),
    ],
    fund: "bloc-nou",
    year: 2021,
    yearStatus: "finalizat",
    buildingType: "monolit",
    condition: "design-individual",
    layout: "decomandat",
    heating: "pardoseala",
    parking: "subteran",
    amenities: [
      "parcare",
      "balcon",
      "lift",
      "mobilat",
      "tehnica",
      "aer-conditionat",
      "incalzire-pardoseala",
      "geamuri-termopan",
      "videointerfon",
      "paza",
      "curte-inchisa",
      "internet",
    ],
    developer: "Exfactor Grup",
    complexSlug: "favorit-residence",
    availableFrom: NOW,
    agentSlug: "cristina-lungu",
    photos: shots(
      ["apt-17", "apt-06", "apt-10", "apt-04", "block-02", "apt-15", "apt-11", "apt-12"],
      "bd. Renașterii Naționale 12"
    ),
    publishedAt: "2026-07-21",
    updatedAt: "2026-07-26",
    featured: false,
  },
  {
    id: "AR-1374",
    slug: "chirie-birou-92-mp-mitropolit-dosoftei-centru-ar-1374",
    deal: "chirie",
    kind: "birou",
    status: "activ",
    flags: [],
    title: {
      ro: "Chirie birou 92 m², str. Mitropolit Dosoftei, Centru",
      ru: "Аренда офиса 92 м², ул. Митрополит Дософтей, Центр",
    },
    description: {
      ro: "Birou la etajul 2 al unei clădiri din 2012, pe o stradă liniștită din Centru, la cinci minute de Ștefan cel Mare. Spațiul e liber și pregătit: se poate intra cu echipa în aceeași săptămână. Potrivit pentru o firmă de 8-14 oameni.\n\nCompartimentare: open space de 52 m², cabinet separat pentru director, sală de ședințe pentru 6 persoane, bucătărie de serviciu, grup sanitar propriu, depozit.\n\nFacilități: climatizare pe zone, cablare de rețea la fiecare post, două linii de internet, mobilier de birou inclus dacă e nevoie, iluminat LED schimbat în 2024, jaluzele.\n\nCondiții: 1 250 € pe lună plus cheltuieli comune de 1,5 €/m². Contract pe minimum un an, garanție de două luni. Trei locuri de parcare în curtea interioară, incluse în chirie.",
      ru: "Офис на 2 этаже здания 2012 года, на тихой улице в Центре, в пяти минутах от Штефана чел Маре. Помещение свободно и готово: заехать с командой можно на той же неделе. Подходит компании на 8-14 человек.\n\nПланировка: open space 52 м², отдельный кабинет для руководителя, переговорная на 6 человек, служебная кухня, собственный санузел, склад.\n\nУдобства: зональное кондиционирование, сетевая проводка на каждое место, две линии интернета, офисная мебель включена при необходимости, LED-освещение заменено в 2024 году, жалюзи.\n\nУсловия: 1 250 € в месяц плюс общедомовые расходы 1,5 €/м². Договор минимум на год, залог за два месяца. Три парковочных места во внутреннем дворе включены в аренду.",
    },
    price: 1250,
    pricePerSqm: 14,
    negotiable: true,
    rooms: 0,
    bathrooms: 1,
    area: 92,
    floor: 2,
    floors: 4,
    ceilingHeight: 300,
    balconies: 0,
    sector: "centru",
    street: "str. Mitropolit Dosoftei 118",
    coords: { lat: 47.0207, lng: 28.8264 },
    mapImage: MAP,
    poi: [
      poi("transport", "Stație troleibuz 2, 10", "Остановка троллейбуса 2, 10", 210),
      poi("magazin", "Linella", "Linella", 190),
      poi("parc", "Grădina Publică Ștefan cel Mare", "Парк Штефана чел Маре", 650),
      poi("policlinica", "Centrul medical Dosoftei", "Медцентр Дософтей", 430),
    ],
    fund: "bloc-nou",
    year: 2012,
    yearStatus: "finalizat",
    buildingType: "monolit",
    condition: "euroreparatie",
    heating: "autonoma",
    parking: "la-sol",
    amenities: [
      "parcare",
      "centrala-termica",
      "mobilat",
      "aer-conditionat",
      "geamuri-termopan",
      "videointerfon",
      "curte-inchisa",
      "internet",
    ],
    availableFrom: NOW,
    agentSlug: "andrei-cebotari",
    photos: shots(
      ["block-02", "office", "apt-19", "apt-14", "apt-10", "block-05", "apt-17", "block-04"],
      "str. Mitropolit Dosoftei 118"
    ),
    publishedAt: "2026-06-27",
    updatedAt: "2026-07-15",
    featured: false,
  },
];

export const PROPERTY_BY_SLUG: Record<string, Property> = Object.fromEntries(
  PROPERTIES.map((p) => [p.slug, p])
);

export const PROPERTY_BY_ID: Record<string, Property> = Object.fromEntries(
  PROPERTIES.map((p) => [p.id, p])
);

export function getProperty(slug: string): Property | undefined {
  return PROPERTY_BY_SLUG[slug];
}

/** "Selecția ARCA" on the homepage. */
export const FEATURED = PROPERTIES.filter((p) => p.featured);

/** "Adăugate săptămâna aceasta" — newest first, by publish date. */
export const NEWEST = [...PROPERTIES].sort((a, b) => b.publishedAt.localeCompare(a.publishedAt));
